/**
 * Render a Godot `custom.py` from a canonical scons-value map.
 *
 * Every key here originates from the catalog allowlist and every value is a
 * member of a closed set ("yes"/"no" or a known enum token), so there is no
 * injection surface. We still (a) re-assert each key matches a strict pattern
 * and (b) emit values as quoted Python string literals, as belt-and-suspenders.
 */
const KEY_PATTERN = /^[a-z0-9_]+$/;

function pyStr(s: string): string {
  return `"${s.replace(/[\\"]/g, "\\$&")}"`;
}

export function renderCustomPy(
  canonicalOptions: Record<string, string>,
): string {
  const lines = [
    "# AUTO-GENERATED by godot-build-service — do not edit.",
    "# Only allowlisted scons options with closed-set values are emitted.",
    "",
  ];
  for (const key of Object.keys(canonicalOptions).sort()) {
    if (!KEY_PATTERN.test(key)) {
      throw new Error(`Refusing to emit unsafe option key: ${key}`);
    }
    lines.push(`${key} = ${pyStr(canonicalOptions[key]!)}`);
  }
  return lines.join("\n") + "\n";
}
